name: Build and Sign APK

on:
  push:
    branches: [ "main" ] # سيعمل التلقائي عند رفع الكود لفرع main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # إعداد Gradle في البيئة
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # --- السطر السحري: توليد ملفات الـ Wrapper تلقائياً من السيرفر ---
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.2

      # فك تشفير ملف التوقيع nasa_new.jks
      - name: Decode Keystore
        run: |
          printf "%s" "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/nasa_new.jks

      # منح صلاحية التنفيذ لـ gradlew الذي تم توليده
      - name: Make Gradlew Executable
        run: chmod +x gradlew

      # بناء نسخة الـ Release الموقعة باستخدام المتغيرات السرية
      - name: Build Signed Release APK
        run: ./gradlew assembleRelease
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # رفع ملف الـ APK الناتج لكي تتمكن من تحميله
      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: AB-Shield-Release
          path: app/build/outputs/apk/release/*.apk
